[workspace]
members = [
  "sample",
  "01-trebuchet",
  "02-cube-conundrum",
  "03-gear-ratios",
  "04-scratchcards",
  "05-if-you-give-a-seed-a-fertilizer",
  "06-wait-for-it",
  "07-camel-cards",
]
resolver = "2"

[workspace.dependencies]
itertools = { version = "*" }
